# Generated by Django 5.1.6 on 2025-05-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
