# Generated by Django 5.0.2 on 2025-05-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0003_book_category_book_description_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(blank=True, choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('N', 'N'), ('SW', 'SW'), ('STS', 'STS'), ('MI', 'MI'), ('FILO', 'FILO')], max_length=100),
        ),
    ]
