# Generated by Django 5.0.2 on 2025-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0004_student_student_class_alter_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_type',
            field=models.CharField(blank=True, choices=[('Generala', 'Generala'), ('Liceu', 'Liceu')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('SW', 'SW'), ('STS', 'STS'), ('MI', 'MI'), ('FILO', 'FILO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(blank=True, choices=[('V-A', 'V-A'), ('V-B', 'V-B'), ('V-C', 'V-C'), ('V-D', 'V-D'), ('V-E', 'V-E'), ('V-F', 'V-F'), ('VI-A', 'VI-A'), ('VI-B', 'VI-B'), ('VI-C', 'VI-C'), ('VI-D', 'VI-D'), ('VI-E', 'VI-E'), ('VI-F', 'VI-F'), ('VII-A', 'VII-A'), ('VII-B', 'VII-B'), ('VII-C', 'VII-C'), ('VII-D', 'VII-D'), ('VII-E', 'VII-E'), ('VII-F', 'VII-F'), ('VIII-A', 'VIII-A'), ('VIII-B', 'VIII-B'), ('VIII-C', 'VIII-C'), ('VIII-D', 'VIII-D'), ('VIII-E', 'VIII-E'), ('VIII-F', 'VIII-F'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=10, null=True),
        ),
    ]
