# Generated by Django 5.0.2 on 2025-05-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0005_student_school_type_alter_student_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='bookborrowing',
            name='loan_duration_days',
            field=models.IntegerField(choices=[(7, '1 Săptămână'), (14, '2 Săptămâni'), (30, '1 Lună'), (60, '2 Luni')], default=14),
        ),
        migrations.AddField(
            model_name='bookborrowing',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookborrowing',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('BORROWED', 'Borrowed'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
