# Generated by Django 5.0.2 on 2025-05-14 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0006_remove_book_isbn_bookborrowing_loan_duration_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrowing',
            name='student_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookborrowing',
            name='status',
            field=models.CharField(choices=[('IN_ASTEPTARE', 'În așteptare'), ('APROBAT', 'Aprobat'), ('GATA_RIDICARE', 'Gata de ridicare'), ('IMPRUMUTAT', 'Împrumutat'), ('RETURNAT', 'Returnat'), ('INTARZIAT', 'Întârziat'), ('RESPINS', 'Respins')], default='IN_ASTEPTARE', max_length=20),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('borrowing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='booklibrary.bookborrowing')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
