# Generated by Django 5.0.2 on 2025-05-14 18:44

from django.db import migrations


def convert_status_values(apps, schema_editor):
    """
    Convert old English status values to new Romanian ones
    """
    BookBorrowing = apps.get_model('booklibrary', 'BookBorrowing')
    
    # Map old status values to new ones
    status_map = {
        'PENDING': 'IN_ASTEPTARE',
        'APPROVED': 'APROBAT',
        'READY_FOR_PICKUP': 'GATA_RIDICARE',
        'BORROWED': 'IMPRUMUTAT',
        'RETURNED': 'RETURNAT',
        'OVERDUE': 'INTARZIAT',
        'REJECTED': 'RESPINS',
    }
    
    # Update all bookborrowings
    for borrowing in BookBorrowing.objects.all():
        if borrowing.status in status_map:
            borrowing.status = status_map[borrowing.status]
            borrowing.save()


def reverse_status_values(apps, schema_editor):
    """
    Revert back to English status values
    """
    BookBorrowing = apps.get_model('booklibrary', 'BookBorrowing')
    
    # Map new status values to old ones
    status_map = {
        'IN_ASTEPTARE': 'PENDING',
        'APROBAT': 'APPROVED',
        'GATA_RIDICARE': 'READY_FOR_PICKUP',
        'IMPRUMUTAT': 'BORROWED',
        'RETURNAT': 'RETURNED',
        'INTARZIAT': 'OVERDUE',
        'RESPINS': 'REJECTED',
    }
    
    # Update all bookborrowings
    for borrowing in BookBorrowing.objects.all():
        if borrowing.status in status_map:
            borrowing.status = status_map[borrowing.status]
            borrowing.save()


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0007_bookborrowing_student_message_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_status_values, reverse_status_values),
    ]
