# Generated by Django 5.0.2 on 2025-05-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0009_alter_message_options_alter_message_borrowing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
