# Generated by Django 5.0.2 on 2025-06-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0010_alter_message_options_message_conversation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('EN', 'Evaluare Națională'), ('BAC', 'Bacalaureat')], max_length=3)),
                ('pdf_file', models.FileField(upload_to='exam_models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
