# Generated by Django 5.0.2 on 2025-06-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0011_exammodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='category',
            field=models.CharField(choices=[('Matematica', 'Matematică'), ('Romana', 'Română')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
