# Generated by Django 5.0.2 on 2025-06-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0014_invitationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationcode',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='used_by',
        ),
    ]
