# Generated by Django 5.0.2 on 2025-06-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0015_remove_invitationcode_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrowing',
            name='has_been_extended',
            field=models.BooleanField(default=False),
        ),
    ]
