# Generated by Django 5.0.2 on 2025-06-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0016_bookborrowing_has_been_extended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('book_added', 'Carte adăugată'), ('stock_updated', 'Stoc actualizat'), ('book_deleted', 'Carte ștearsă'), ('book_requested', 'Carte solicitată'), ('request_approved', 'Cerere aprobată'), ('request_rejected', 'Cerere respinsă'), ('book_returned', 'Carte returnată'), ('extension_requested', 'Extindere solicitată')], max_length=20),
        ),
    ]
