# Generated by Django 5.0.2 on 2025-06-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0017_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('carte', 'Carte'), ('manual', 'Manual')], default='carte', max_length=10),
        ),
    ]
