# Generated by Django 5.0.2 on 2025-06-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0018_add_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_class',
            field=models.CharField(blank=True, choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=10, null=True, verbose_name='Clasă'),
        ),
    ]
