# Generated by Django 5.0.2 on 2025-07-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0020_book_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookborrowing',
            name='status',
            field=models.CharField(choices=[('IN_ASTEPTARE', 'În așteptare'), ('APROBAT', 'Aprobat'), ('GATA_RIDICARE', 'Gata de ridicare'), ('IMPRUMUTAT', 'Împrumutat'), ('RETURNAT', 'Returnat'), ('INTARZIAT', 'Întârziat'), ('RESPINS', 'Respins'), ('ANULATA', 'Anulată')], default='IN_ASTEPTARE', max_length=20),
        ),
    ]
